service: dio-aws-crud-clientes
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:Scan
                - dynamodb:DeleteItem
              Resource:
                - arn:aws:dynamodb:us-east-1:192482787607:table/clientes

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

  createCliente:
    handler: src/createCliente.handler
    events:
      - http:
          path: cliente
          method: post
          cors: true

  getCliente:
    handler: src/getCliente.handler
    events:
      - http:
          path: cliente/{id}
          method: get
          cors: true

  updateCliente:
    handler: src/updateCliente.handler
    events:
      - http:
          path: cliente/{id}
          method: put
          cors: true

  deleteCliente:
    handler: src/deleteCliente.handler
    events:
      - http:
          path: cliente/{id}
          method: delete
          cors: true

resources:
  Resources:
    ClienteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: clientes
        AttributeDefinitions:
         - AttributeName: id
           AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH        
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5